src/main/java/br/com/erudio/model/User.java
package br.com.erudio.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.DiscriminatorFormula;
import org.hibernate.validator.constraints.NotBlank;
import org.joda.time.LocalDateTime;

@Entity
@Table(name = "usuario")
@NamedQueries({
        @NamedQuery(name = "Usuario.findByEmailAndAtivo", query = "SELECT DISTINCT u FROM Usuario u WHERE u.email = :email AND u.ativo = true ORDER BY u.email")
})
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@Inheritance(strategy=InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name="discriminator", discriminatorType=DiscriminatorType.STRING)
//@DiscriminatorFormula("case when Usuario is null then 0 else Usuario end") 
@DiscriminatorValue(value="U")
public class User implements Model<Long>, Serializable {

	private static final long serialVersionUID = 1L;

	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull
    @Column(name = "data_hora_criacao")
    private Date dataHoraCriacao;

    @NotNull
    @Column(length = 1000)
    @Size(min = 1, max = 1000)
    private String nome;

    @NotNull
    @NotBlank
    @org.hibernate.validator.constraints.Email
    @Column(length = 1000)
    private String email;

    @NotNull
    @Column(length = 1000)
    private String senha;

    @Column(name = "token_nova_senha", length = 128)
    private String tokenNovaSenha;

    @Column(name = "data_expiracao_token_nova_senha")
    private Date dataExpiracaoTokenNovaSenha;

    @NotNull
    @Column
    private boolean ativo = true;

    @Transient
    private String senhaConfirmacao;

    public User() {
        dataHoraCriacao = LocalDateTime.now().toDate();
    }

    @Override
    public Long getId() {
        return this.id;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof User)) {
            return false;
        }
        User other = (User) obj;
        if (id != null) {
            if (!id.equals(other.id)) {
                return false;
            }
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        return result;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }

    public Date getDataHoraCriacao() {
        return dataHoraCriacao;
    }

    public void setDataHoraCriacao(Date dataHoraCriacao) {
        this.dataHoraCriacao = dataHoraCriacao;
    }

    public String getTokenNovaSenha() {
        return tokenNovaSenha;
    }

    public void setTokenNovaSenha(String tokenNovaSenha) {
        this.tokenNovaSenha = tokenNovaSenha;
    }

    public Date getDataExpiracaoTokenNovaSenha() {
        return dataExpiracaoTokenNovaSenha;
    }

    public void setDataExpiracaoTokenNovaSenha(Date dataExpiracaoTokenNovaSenha) {
        this.dataExpiracaoTokenNovaSenha = dataExpiracaoTokenNovaSenha;
    }

    public String getSenhaConfirmacao() {
        return senhaConfirmacao;
    }

    public void setSenhaConfirmacao(String senhaConfirmacao) {
        this.senhaConfirmacao = senhaConfirmacao;
    }
    
    public boolean isAtivo() {
		return ativo;
	}

	public void setAtivo(boolean ativo) {
		this.ativo = ativo;
	}

	public String getAtivoString() {
        return ativo ? "SIM" : "NÃO";
    }
}

src/main/java/br/com/erudio/controller/UsuarioController.java
package br.com.erudio.controller;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;
import java.util.List;

import com.ocpsoft.pretty.faces.annotation.URLAction;
import com.ocpsoft.pretty.faces.annotation.URLMapping;
import com.ocpsoft.pretty.faces.annotation.URLMappings;

import br.com.erudio.model.User;
import br.com.erudio.service.UserService;

import org.omnifaces.util.Messages;

@Named
@ViewScoped
@URLMappings(mappings = {
        @URLMapping(id = "usuarios", pattern = "/usuarios/", viewId = "/jsf/pages/protegido/geral/usuario/usuarios.xhtml"),
        @URLMapping(id = "usuario", pattern = "/usuario/id/#{usuarioController.usuarioId}/", viewId = "/jsf/pages/protegido/geral/usuario/usuario.xhtml"),
        @URLMapping(id = "usuario-novo", pattern = "/usuario/novo/", viewId = "/jsf/pages/protegido/geral/usuario/usuario.xhtml")
})
public class UsuarioController implements Serializable {
    private static final long serialVersionUID = 1L;

    @Inject
    private UserService usuarioService;

    private List<User> usuarios;
    private Long usuarioId;
    private User usuario;

    @URLAction(mappingId = "usuarios", onPostback = false)
    public void idUsuarios() {
        usuarios = usuarioService.findAll();
    }

    @URLAction(mappingId = "usuario", onPostback = false)
    public void idUsuario() {
        usuario = usuarioService.findById(usuarioId);
    }

    @URLAction(mappingId = "usuario-novo", onPostback = false)
    public void idUsuarioNovo() {
        usuario = new User();
    }

    public void salvar() {
        usuario = usuarioService.salvar(usuario);
        Messages.addGlobalInfo("Usuário salvo com sucesso!");
    }

    public void resetarSenha() {
        usuario = usuarioService.resetSenhaAndEnviaEmailUsuario(usuario);
        Messages.addGlobalInfo("Senha resetada com sucesso e o email com a nova senha será enviada!");
    }

    public List<User> getUsuarios() {
        return usuarios;
    }

    public void setUsuarios(List<User> usuarios) {
        this.usuarios = usuarios;
    }

    public Long getUsuarioId() {
        return usuarioId;
    }

    public void setUsuarioId(Long usuarioId) {
        this.usuarioId = usuarioId;
    }

    public User getUsuario() {
        return usuario;
    }

    public void setUsuario(User usuario) {
        this.usuario = usuario;
    }
}

src/main/webapp/pages/protegido/geral/usuario/usuario.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:lj="http://xmlns.jcp.org/jsf/composite/components" xmlns:pretty="http://ocpsoft.com/prettyfaces">
<ui:composition template="/resources/templates/template-core.xhtml">
    <ui:define name="cabecalho">
        Usuário #{usuarioController.usuario.nome}
    </ui:define>
    <ui:define name="conteudo">
        <h:form id="form" enctype="multipart/form-data">
            <lj:messages/>

            <div class="form-group">
                <label>Nome</label>
                <h:inputText value="#{usuarioController.usuario.nome}" styleClass="form-control"/>
            </div>
            <div class="form-group">
                <label>Email</label>
                <h:inputText value="#{usuarioController.usuario.email}" styleClass="form-control"/>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <h:commandLink action="#{usuarioController.salvar}" styleClass="btn btn-default">
                        <i class="glyphicon glyphicon-floppy-disk"></i> salvar
                    </h:commandLink>
                    <h:commandLink action="#{usuarioController.resetarSenha}" styleClass="btn btn-default">
                        <i class="glyphicon glyphicon-floppy-disk"></i> resetar senha
                    </h:commandLink>
                    <pretty:link mappingId="usuarios" styleClass="btn btn-default">
                        <i class="glyphicon glyphicon-arrow-left"></i> voltar
                    </pretty:link>
                </div>
            </div>
        </h:form>
    </ui:define>

</ui:composition>

</html>

src/main/webapp/pages/protegido/geral/usuario/usuarios.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:lj="http://xmlns.jcp.org/jsf/composite/components" xmlns:pretty="http://ocpsoft.com/prettyfaces">
<ui:composition template="/resources/templates/template-core.xhtml">
    <ui:define name="cabecalho">
        Usuários
    </ui:define>
    <ui:define name="conteudo">
        <h:form id="form">
            <lj:messages/>

            <div class="row">
                <div class="col-lg-12">
                    <pretty:link mappingId="usuario-novo" styleClass="btn btn-default">
                        <i class="glyphicon glyphicon-plus"></i> novo
                    </pretty:link>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <p:dataTable value="#{usuarioController.usuarios}" var="usuario"
                                 paginator="true" rows="20" paginatorPosition="bottom">
                        <p:column headerText="Nome" filterMatchMode="contains" filterBy="#{usuario.nome}">
                            #{usuario.nome}
                        </p:column>
                        <p:column headerText="Email" filterMatchMode="contains" filterBy="#{usuario.email}">
                            #{usuario.email}
                        </p:column>
                        <p:column headerText="Ativo" filterMatchMode="contains" filterBy="#{usuario.ativoString}">
                            #{usuario.ativoString}
                        </p:column>
                        <p:column headerText="Ações">
                            <pretty:link mappingId="usuario" styleClass="btn btn-default">
                                <i class="glyphicon glyphicon-pencil"></i> editar
                                <f:param value="#{usuario.id}"/>
                            </pretty:link>
                        </p:column>
                    </p:dataTable>
                </div>
            </div>
        </h:form>
    </ui:define>

</ui:composition>

</html>