src/main/java/br/com/erudio/controller/BaseController.java
package br.com.erudio.controller;

import javax.enterprise.context.SessionScoped;
import javax.enterprise.inject.Produces;
import javax.faces.FacesException;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.Serializable;
import java.net.URI;
import java.net.URISyntaxException;

import org.apache.shiro.SecurityUtils;
import org.apache.shiro.subject.Subject;
import org.slf4j.Logger;

import br.com.erudio.cdi.annotation.LoggedUser;
import br.com.erudio.model.User;
import br.com.erudio.util.Constants;

@Named
@SessionScoped
public class BaseController implements Serializable {
    private static final long serialVersionUID = 1L;

    @Inject
    private transient Logger logger;

    private User usuarioLogado;

    /**
     * protected usar com @Inject
     */
    @Named("usuarioLogado")
    @Produces
    @LoggedUser
    protected User getUsuarioLogado() {
        final Subject subject = SecurityUtils.getSubject();

        if (!subject.isAuthenticated()) {
            return null;
        }

        if (usuarioLogado == null) {
            usuarioLogado = subject.getPrincipals().oneByType(User.class);
        }
        return usuarioLogado;
    }

    private void redirect(String page) {
        try {
            if (!getHttpServletResponse().isCommitted()) {
                logger.info("redirect to " + page);
                getHttpServletResponse().sendRedirect(getContextPath() + page);
            }
        } catch (IOException e) {
            logger.error("Erro ao redirecionar para " + page, e);
        }
    }

    public String getRealPath() {
        try {
            ExternalContext ec = getExternalContext();
            URI uri = new URI(ec.getRequestScheme(), null,
                    ec.getRequestServerName(), ec.getRequestServerPort(), null,
                    null, null);
            return uri.toASCIIString();
        } catch (URISyntaxException e) {
            throw new FacesException(e);
        }
    }

    public void redirectPageNotFound() {
        redirect("/pagina-nao-existe/");
    }

    public void redirectPageAccessNotAllowed() {
        redirect("/acesso-nao-autorizado/");
    }

    public boolean isAdminTS() {
        return getUsuarioLogado().getEmail().equalsIgnoreCase(Constants.ERUDIO_MAIL);
    }

    public void checkAdminTS() {
        if (!isAdminTS()) {
            redirectPageAccessNotAllowed();
        }
    }

    public FacesContext getFacesContext() {
        return FacesContext.getCurrentInstance();
    }

    public ExternalContext getExternalContext() {
        return getFacesContext().getExternalContext();
    }

    public HttpServletRequest getHttpServletRequest() {
        return (HttpServletRequest) getExternalContext().getRequest();
    }

    public HttpServletResponse getHttpServletResponse() {
        return (HttpServletResponse) getExternalContext().getResponse();
    }

    public String getContextPath() {
        return getHttpServletRequest().getContextPath();
    }

    public String getRequestURL() {
        return getHttpServletRequest().getRequestURL().toString();
    }
}

src/main/webapp/resources/templates/template-clean.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets">
<ui:composition template="template.xhtml"
                xmlns:lj="http://java.sun.com/jsf/composite/components">

    <ui:define name="corpo">

        <lj:messages id="msgs"/>

        <p>
            <ui:insert name="alerta"></ui:insert>
        </p>
    </ui:define>
</ui:composition>
</html>

src/main/webapp/resources/templates/template-core.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:lj="http://java.sun.com/jsf/composite/components" xmlns:pretty="http://ocpsoft.com/prettyfaces">

<ui:composition template="template.xhtml">
    <ui:define name="css">
        <h:outputStylesheet name="assets/css/dashboard.css" rel="stylesheet"/>
    </ui:define>
    <ui:define name="corpo">

        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <pretty:link mappingId="home" styleClass="navbar-brand">ERUDIO Java</pretty:link>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <pretty:link mappingId="perfil">Perfil</pretty:link>
                        </li>
                        <li>
                            <h:outputLink value="#{request.contextPath}/sair/"><i
                                    class="glyphicon glyphicon-log-out"></i> Sair</h:outputLink>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-12 sidebar-mobile">
                    <lj:menu/>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3 col-md-2 sidebar">
                    <lj:menu/>
                </div>
                <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                    <h1 class="page-header">
                        <ui:insert name="cabecalho"></ui:insert>
                    </h1>

                    <ui:insert name="conteudo">
                    </ui:insert>
                </div>
            </div>
        </div>

        <ui:insert name="footer">
            <div class="row">
                <div class="col-xs-12">
                    <footer class="al-right center-phone">
                        <hr/>
                        <a href="http://erudio.com.br/" target="_blank"><img
                                src="#{request.contextPath}/resources/assets/img/powered-by-ts-3.gif"
                                alt="TecSinapse"/></a>
                    </footer>
                </div>
            </div>
        </ui:insert>

    </ui:define>
</ui:composition>

</html>

src/main/webapp/resources/templates/template.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
        >

<f:view>
    <h:head>
        <f:facet name="first">
            <meta charset="utf-8"></meta>
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
            <title><ui:insert name="title">ERUDIO Java</ui:insert></title>

            <link rel="icon" type="image/vnd.microsoft.icon"
                  href="#{request.contextPath}/resources/images/favicon.ico"/>
            <link rel="SHORTCUT ICON" type="image/vnd.microsoft.icon"
                  href="#{request.contextPath}/resources/images/favicon.ico"/>

            <meta name="description" content=""></meta>
            <meta name="keywords" content=""></meta>
            <meta name="author" content="erudio"></meta>

            <meta name="viewport" content="width=device-width,initial-scale=1.0"></meta>

            <!-- Adiciona todos jqueries disponíveis para evitar conflitos será utilizado o último a ser declarado-->
            <!-- não chamar jQuery.noConflict(); -->
            <h:outputScript library="primefaces" name="jquery/jquery.js"/>
            <h:outputScript name="assets/js/jquery-1.11.1.min.js"/>
        </f:facet>

        <h:outputStylesheet name="assets/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>

        <ui:insert name="css">
        </ui:insert>

        <h:outputScript name="assets/bootstrap/js/bootstrap.min.js"/>

        <ui:insert name="js"></ui:insert>
    </h:head>

    <h:body>
        <ui:insert name="metadata">
        </ui:insert>

        <ui:insert name="corpo">
        </ui:insert>
    </h:body>
</f:view>
</html>